sonar.projectKey=PrieTorres_correctio-app
sonar.organization=prietorres

sonar.sources=apps/web/src
sonar.tests=apps/web/src,apps/web/cypress
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.cy.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.sourceEncoding=UTF-8
